<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>WeiGo 后台管理</title>
    <meta content="Admin Dashboard" name="description" />
    <meta content="Mannatthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="shortcut icon" href="<?php echo MAIN_SERVER."/public/images/favicon.ico";?>">

    <!-- jvectormap -->
    <link href="<?php echo MAIN_SERVER.'/public/css/admin/plugins/jvectormap/jquery-jvectormap-2.0.2.css';?>" rel="stylesheet">

    <link href="<?php echo MAIN_SERVER.'/public/css/admin/bootstrap.min.css';?>" rel="stylesheet" type="text/css">
    <link href="<?php echo MAIN_SERVER.'/public/css/admin/icons.css';?>" rel="stylesheet" type="text/css">
    <link href="<?php echo MAIN_SERVER.'/public/css/admin/style.css';?>" rel="stylesheet" type="text/css">
</head>


<body class="fixed-left">

<!-- Loader -->
<div id="preloader"><div id="status"><div class="spinner"></div></div></div>

<!-- Begin page -->
<div id="wrapper">

    <!-- ========== Left Sidebar Start ========== -->
    <div class="left side-menu">
        <button type="button" class="button-menu-mobile button-menu-mobile-topbar open-left waves-effect">
            <i class="ion-close"></i>
        </button>

        <!-- LOGO -->
        <div class="topbar-left">
            <div class="text-center">
                <a href="index" class="logo"><i class="mdi mdi-assistant"></i> WeiGO</a>
                <!-- <a href="index.html" class="logo"><img src="assets/images/logo.png" height="24" alt="logo"></a> -->
            </div>
        </div>

        <div class="sidebar-inner slimscrollleft">

            <div id="sidebar-menu">
                <ul>

                    <!--<li>
                        <a href="index.html" class="waves-effect"><i class="mdi mdi-airplay"></i><span> Dashboard</span></a>
                    </li>
                    <li>
                        <a href="exchange.html" class="waves-effect"><i class="mdi mdi-swap-horizontal"></i><span> Exchange </span></a>
                    </li>
                    <li>
                        <a href="mywallet.html" class="waves-effect"><i class="mdi mdi-wallet"></i><span> My Wallet </span></a>
                    </li>
                    <li>
                        <a href="calendar.html" class="waves-effect"><i class="mdi mdi-calendar-clock"></i><span> Calendar </span></a>
                    </li>-->
                    <li>
                        <a href="/admin/list/index" class="waves-effect"><i class="mdi mdi-chart-areaspline"></i><span> 统计列表 </span></a>
                    </li>
                    <!--<li>
                        <a href="ico.html" class="waves-effect"><i class="mdi mdi-biohazard"></i><span> ICO Landing </span></a>
                    </li>
                    <li>
                        <a href="setting.html" class="waves-effect"><i class="mdi mdi-settings"></i><span> Settings </span></a>
                    </li>-->
                    <li>
                        <a href="/admin/login/logout" class="waves-effect"><i class="mdi mdi-power"></i><span> Logout </span></a>
                    </li>

                </ul>
            </div>
            <div class="clearfix"></div>
        </div> <!-- end sidebarinner -->
    </div>
    <!-- Left Sidebar End -->

    <!-- Start right Content here -->

    <div class="content-page">
        <!-- Start content -->
        <div class="content">

            <?php echo $content;?>

        </div> <!-- content -->

        <footer class="footer">
            © 2018 WeiGo by 六枣先生
        </footer>

    </div>
    <!-- End Right content here -->

</div>
<!-- END wrapper -->


<!-- jQuery  -->
<script src="<?php echo MAIN_SERVER.'/public/js/admin/jquery.min.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/popper.min.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/bootstrap.min.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/modernizr.min.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/detect.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/fastclick.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/jquery.slimscroll.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/jquery.blockUI.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/waves.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/jquery.nicescroll.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/jquery.scrollTo.min.js';?>"></script>

<!--Morris Chart-->
<script src="<?php echo MAIN_SERVER.'/public/js/admin/plugins/flot-chart/jquery.flot.min.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/plugins/flot-chart/jquery.flot.time.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/plugins/flot-chart/curvedLines.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/plugins/flot-chart/jquery.flot.pie.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/plugins/morris/morris.min.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/plugins/raphael/raphael-min.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/plugins/jquery-sparkline/jquery.sparkline.min.js';?>"></script>

<script src="<?php echo MAIN_SERVER.'/public/js/admin/plugins/jvectormap/jquery-jvectormap-2.0.2.min.js';?>"></script>
<script src="<?php echo MAIN_SERVER.'/public/js/admin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js';?>"></script>


<script src="<?php echo MAIN_SERVER.'/public/js/admin/pages/crypto-dash.init.js';?>"></script>

<!-- App js -->
<script src="<?php echo MAIN_SERVER.'/public/js/admin/app.js';?>"></script>
<script>

    $(document).ready(function() {
        $("#boxscroll").niceScroll({cursorborder:"",cursorcolor:"#cecece",boxzoom:true});
        $("#boxscroll2").niceScroll({cursorborder:"",cursorcolor:"#cecece",boxzoom:true});
    });

</script>


</body>
</html>